// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyEaeJ6TspeWiLNl-0qDqZJxQ83v8H4gk',
    appId: '1:836220697387:web:cf7a1c314d3bd72567a36e',
    messagingSenderId: '836220697387',
    projectId: 'project-one-7ac2e',
    authDomain: 'project-one-7ac2e.firebaseapp.com',
    storageBucket: 'project-one-7ac2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHzXTTWJsuruAo4BP4lzwsRIRkz7eZswE',
    appId: '1:836220697387:android:5f910ad43e16ebdc67a36e',
    messagingSenderId: '836220697387',
    projectId: 'project-one-7ac2e',
    storageBucket: 'project-one-7ac2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeDyQE_nH-vw3NfOa7oVTxXYaTtQR6cNM',
    appId: '1:836220697387:ios:bec77368ba369d7567a36e',
    messagingSenderId: '836220697387',
    projectId: 'project-one-7ac2e',
    storageBucket: 'project-one-7ac2e.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeDyQE_nH-vw3NfOa7oVTxXYaTtQR6cNM',
    appId: '1:836220697387:ios:bec77368ba369d7567a36e',
    messagingSenderId: '836220697387',
    projectId: 'project-one-7ac2e',
    storageBucket: 'project-one-7ac2e.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyEaeJ6TspeWiLNl-0qDqZJxQ83v8H4gk',
    appId: '1:836220697387:web:5ecc1b2ef7b5504067a36e',
    messagingSenderId: '836220697387',
    projectId: 'project-one-7ac2e',
    authDomain: 'project-one-7ac2e.firebaseapp.com',
    storageBucket: 'project-one-7ac2e.firebasestorage.app',
  );
}
